server:
  port: 8090
management:
  port: 8762
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${spring.cloud.client.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
  instance:
    metadataMap:
      management-url: ${spring.cloud.client.hostname}:${management.port}
      management-port: ${management.port}
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    hostname: ${spring.cloud.client.hostname}
  server:
    waitTimeInMsWhenSyncEmpty: 0